apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      run: scheduler
  replicas: 2
  template:
    metadata:
      labels:
        run: scheduler
    spec:
      containers:
      - name: scheduler
        ports:
        - containerPort: 8000
